DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS party CASCADE;
DROP TABLE IF EXISTS office CASCADE;
DROP TABLE IF EXISTS candidates CASCADE;
DROP TABLE IF EXISTS vote CASCADE;
DROP TABLE IF EXISTS petitions CASCADE;